// Trip data — single source of truth for the Vietnam site
window.TRIP_DATA = {
  meta: {
    title: "The Doos · Vietnam",
    subtitle: "June 2026",
    travelers: ["Christine", "Ashraf", "Jason", "Chris"],
    departDate: "2026-06-11T10:35:00+10:00",
    returnDate: "2026-06-23T22:15:00+10:00",
    nights: 13,
    cities: 2,
  },

  flights: [
    {
      kind: "Outbound",
      from: { city: "Melbourne", code: "MEL", terminal: "T2" },
      to: { city: "Ho Chi Minh City", code: "SGN", terminal: "T2" },
      date: "Thursday 11 June 2026",
      depart: "10:35",
      arrive: "16:15",
      duration: "8h 40m",
      carrier: "Vietnam Airlines",
      flightNo: "VN780",
      aircraft: "Airbus A350",
      note: "Vietnam is 3 hours behind Melbourne. When we land at 4:15 PM your body thinks it's 7:15 PM — manageable. Tan Son Nhat to the hotel in District 3 is about 45 minutes.",
    },
    {
      kind: "Internal",
      from: { city: "Ho Chi Minh City", code: "SGN", terminal: "T1" },
      to: { city: "Hanoi", code: "HAN", terminal: "T1" },
      date: "Monday 15 June 2026",
      depart: "20:30",
      arrive: "22:35",
      duration: "2h 5m",
      carrier: "Vietnam Airlines",
      flightNo: "VN256",
      aircraft: "",
      note: "Late arrival — transfer pre-booked so we're not figuring it out at midnight half asleep.",
    },
    {
      kind: "Return",
      from: { city: "Hanoi", code: "HAN", terminal: "T2" },
      to: { city: "Melbourne", code: "MEL", terminal: "T2" },
      date: "Tuesday 23 June 2026",
      depart: "09:55",
      arrive: "22:15",
      duration: "9h 20m",
      carrier: "Vietnam Airlines",
      flightNo: "VN779",
      aircraft: "Airbus A350-900",
      note: "Hotel checkout 7:30 AM sharp. Yes I know. Last day. Sorry.",
    },
  ],

  days: [
    {
      n: 1, date: "11 Jun", weekday: "Thu", city: "Ho Chi Minh City", title: "Arrival Day",
      tags: ["Travel", "Food", "Easy"], mood: "evening",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hcmc-night.jpg",
      activities: [
        { time: "16:15", mood: "afternoon", title: "Land at Tan Son Nhat", detail: "About 45 minutes by Grab from the airport to the hotel in District 3. Checked in by 5:15pm." },
        { time: "Evening", mood: "evening", title: "Dinner nearby", detail: "Freshen up and find dinner close to the hotel. Don't go too hard on night one." },
        { time: "Later", mood: "night", title: "Rooftop pool (Level 19)", detail: "If anyone's feeling more awake than expected, the rooftop opens until 22:00." },
      ],
      tip: "Use the Grab app for taxis, not the random ones at the airport. Set it up before we land.",
    },
    {
      n: 2, date: "12 Jun", weekday: "Fri", city: "Ho Chi Minh City", title: "History & Markets",
      tags: ["History", "Shopping", "Food"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/banh-mi.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "War Remnants Museum", detail: "10-minute Grab from the hotel, or 20-min walk if cool enough. Heavy emotionally — take your time. Get there before the heat kicks in.", link: "War Remnants Museum" },
        { time: "Midday", mood: "afternoon", title: "Hotel lunch & cheeky drink", detail: "Midday break. Heat is no joke — grab a cold one and re-set before round two." },
        { time: "Afternoon", mood: "afternoon", title: "Ben Thanh Market", detail: "5-minute Grab, walkable in 15. Souvenirs, coffee, scarves, snacks. Haggle hard — start low and walk away if they won't budge.", link: "Ben Thanh Market" },
        { time: "Evening", mood: "evening", title: "Night market street food", detail: "Ben Thanh turns into a street food market after 6pm. Great way to spend the evening." },
      ],
    },
    {
      n: 3, date: "13 Jun", weekday: "Sat", city: "Ho Chi Minh City", title: "Cu Chi Tunnels",
      tags: ["History", "Outdoors"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/cu-chi.jpg",
      region: {
        base: { name: "Ho Chi Minh City", x: 380, y: 230 },
        dest: { name: "Cu Chi Tunnels", x: 130, y: 80 },
        bearing: "Northwest",
        distance: "70 km",
        duration: "~1.5 hr drive",
        transport: "Small-group coach",
        terrain: "jungle",
      },
      activities: [
        { time: "08:00", mood: "morning", title: "Tour bus pickup", detail: "1.5 hours northwest of the city. Booked a small group tour, not the giant 40-person buses." },
        { time: "Late morning", mood: "morning", title: "Cu Chi Tunnels", detail: "Jason, you can crawl through the actual tunnels if you want. I'd take the enlarged tourist version unless you're keen to really test yourself.", link: "Cu Chi Tunnels" },
        { time: "Afternoon", mood: "afternoon", title: "Hotel + rooftop pool", detail: "Back by mid-afternoon. You'll have earnt it." },
      ],
      tip: "Everything at your own pace. Plenty of shade and benches, no rushing.",
    },
    {
      n: 4, date: "14 Jun", weekday: "Sun", city: "Ho Chi Minh City", title: "Mekong Delta",
      tags: ["Nature", "Food", "Relaxed"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/mekong-boat.jpg",
      region: {
        base: { name: "Ho Chi Minh City", x: 360, y: 70 },
        dest: { name: "Mỹ Tho · Mekong", x: 160, y: 230 },
        bearing: "South",
        distance: "70 km",
        duration: "~1.5 hr drive",
        transport: "Coach + canoe",
        terrain: "river",
      },
      activities: [
        { time: "07:30", mood: "morning", title: "Coach to the delta", detail: "1.5 hours south of HCMC. Canals, rice paddies, coconut palms, small fishing villages." },
        { time: "Morning", mood: "morning", title: "Coconut candy factory", detail: "Mum — this one's for you. Plus a bee farm and a tropical fruit garden with live traditional music." },
        { time: "Afternoon", mood: "afternoon", title: "Canal canoe ride", detail: "Local rowers take you through the jungle. Just sit back. Lunch included.", link: "Mekong Delta Boat Tour" },
        { time: "Evening", mood: "evening", title: "Last dinner in HCMC", detail: "Let's find somewhere good. Last night in the south." },
      ],
    },
    {
      n: 5, date: "15 Jun", weekday: "Mon", city: "HCMC → Hanoi", title: "Fly North",
      tags: ["Relax", "Travel"], mood: "evening",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hanoi-old-quarter.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Free morning", detail: "Sleep in, rooftop pool one last time, leisurely breakfast." },
        { time: "17:30", mood: "evening", title: "Leave for airport", detail: "Tan Son Nhat is ~40 min from District 3. Aim to leave by 5:30pm for the 8:30pm departure." },
        { time: "22:35", mood: "night", title: "Land in Hanoi", detail: "Pre-booked transfer straight to the Old Quarter. Noi Bai is ~45 min away. Bed." },
      ],
    },
    {
      n: 6, date: "16 Jun", weekday: "Tue", city: "Hanoi", title: "Old Quarter & Hoa Lo",
      tags: ["History", "Food", "Shopping"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hoan-kiem.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Slow breakfast", detail: "Hanoi feels completely different — older, cooler, more French colonial. Just take it in." },
        { time: "Late morning", mood: "morning", title: "Hoa Lo Prison", detail: "10-minute walk from most Old Quarter hotels. Covers French colonial era and the Vietnam War. Get the audio guide.", link: "Hoa Lo Prison" },
        { time: "Afternoon", mood: "afternoon", title: "Hoan Kiem Lake", detail: "10 min on foot from Hoa Lo. Little temple on an island connected by a red bridge — really beautiful." },
        { time: "Afternoon", mood: "afternoon", title: "Old Quarter wander", detail: "The 36 streets. You could walk it end-to-end in 20 min — you won't." },
        { time: "Evening", mood: "evening", title: "Street food + egg coffee", detail: "Try the egg coffee. Tastes like liquid tiramisu." },
      ],
    },
    {
      n: 7, date: "17 Jun", weekday: "Wed", city: "Ha Long Bay", title: "Mon Cheri Cruise",
      tags: ["Nature", "Food", "Unmissable"], mood: "day", star: true,
      hero: "https://doosyy.github.io/Vietnam-Trip/img/halong-bay.jpg",
      region: {
        base: { name: "Hanoi · Old Quarter", x: 80, y: 150 },
        dest: { name: "Hạ Long City", x: 430, y: 165 },
        bearing: "East",
        distance: "170 km",
        duration: "~3.5 hr drive",
        transport: "Coach → cruise",
        terrain: "bay",
      },
      activities: [
        { time: "08:00", mood: "morning", title: "Coach pickup", detail: "3.5 hours to Ha Long City. Arrive at the harbour around 11:30am." },
        { time: "12:00", mood: "afternoon", title: "Board Mon Cheri + lunch on deck", detail: "The moment the limestone karsts appear around you, everyone goes quiet. It does that to people." },
        { time: "Afternoon", mood: "afternoon", title: "Cave visit + optional kayaking", detail: "Kayaking is completely optional — you can sit on the deck and let the views do the work." },
        { time: "Sunset", mood: "evening", title: "Sunset on deck + seafood dinner", detail: "Drinks on deck, dinner on board, sleep on the boat.", link: "Ha Long Bay Cruise" },
      ],
    },
    {
      n: 8, date: "18 Jun", weekday: "Thu", city: "Ha Long Bay → Hanoi", title: "Sunrise on the Bay",
      tags: ["Nature"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/halong-bay.jpg",
      activities: [
        { time: "Sunrise", mood: "morning", title: "Sunrise on deck", detail: "Set an alarm. Worth it." },
        { time: "Morning", mood: "morning", title: "Breakfast + sail back", detail: "Slow morning on board before disembarking." },
        { time: "Afternoon", mood: "afternoon", title: "Coach back to Hanoi", detail: "3.5 hours. Back in the Old Quarter by early evening." },
      ],
    },
    {
      n: 9, date: "19 Jun", weekday: "Fri", city: "Hanoi", title: "Temple & Shopping",
      tags: ["Culture", "Shopping", "Easy"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hanoi-old-quarter.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Slow start", detail: "No alarm. Proper breakfast after two days on the bay." },
        { time: "Late morning", mood: "morning", title: "Temple of Literature", detail: "15-min Grab from the Old Quarter. Vietnam's first university — built in 1070. Hire a guide; the history is what makes it.", link: "Temple of Literature" },
        { time: "Afternoon", mood: "afternoon", title: "Hang Gai & Dong Xuan", detail: "Old Quarter shopping. Walkable from the hotel." },
        { time: "Evening", mood: "evening", title: "Cha Ca La Vong", detail: "Turmeric fish cooked at the table with dill. Worth trying." },
      ],
    },
    {
      n: 10, date: "20 Jun", weekday: "Sat", city: "Ninh Binh", title: "Ha Long on Land",
      tags: ["Nature", "History", "Scenic"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/ninh-binh.jpg",
      region: {
        base: { name: "Hanoi · Old Quarter", x: 380, y: 65 },
        dest: { name: "Trang An · Ninh Binh", x: 175, y: 235 },
        bearing: "South",
        distance: "95 km",
        duration: "~2 hr drive",
        transport: "Private coach",
        terrain: "karst",
      },
      activities: [
        { time: "07:30", mood: "morning", title: "Drive south", detail: "2 hours to Ninh Binh. Called the inland Ha Long Bay — same dramatic limestone karsts but surrounded by rice paddies." },
        { time: "Morning", mood: "morning", title: "Trang An boat trip", detail: "Local rowers take us through caves, past ancient temples, under limestone cliffs. ~2.5 hours. Sit and take it in.", link: "Ninh Binh & Trang An" },
        { time: "Afternoon", mood: "afternoon", title: "Lunch in town", detail: "Local speciality is goat meat. Don't knock it until you've tried it." },
        { time: "Evening", mood: "evening", title: "Back to Hanoi", detail: "Quiet night." },
      ],
    },
    {
      n: 11, date: "21 Jun", weekday: "Sun", city: "Hanoi", title: "Chill & Street Food",
      tags: ["Food", "Relaxed"], mood: "evening",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/street-food.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Coffee by Hoan Kiem", detail: "10 min from the hotel. Locals do tai chi here. Just sit and watch the city wake up." },
        { time: "Afternoon", mood: "afternoon", title: "Spa, shopping & bar hopping", detail: "Mum — strongly recommend a spa. Vietnamese massage is exceptional and very affordable. Plenty of boutiques in the Old Quarter, then drinks before dinner. Jason can find his own trouble." },
        { time: "18:30", mood: "evening", title: "Old Quarter street food tour", detail: "~3 hours. Banh Mi, egg coffee, spring rolls, Che. Go in with an open mind on that last one.", link: "Street Food Tour" },
      ],
      tip: "Egg coffee is a Hanoi original — Cafe Giang on Hang Gai Street is the famous one, but honestly most cafes do a great version. Don't go out of your way; grab one whenever you see it.",
    },
    {
      n: 12, date: "22 Jun", weekday: "Mon", city: "Hanoi", title: "Flex Day",
      tags: ["Food", "Free"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/pho.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Open morning — shopping", detail: "By this point we'll know what we feel like. Good morning for last-minute shopping in the Old Quarter — souvenirs, silk, art prints, anything you've been eyeing all week. Don't over-plan it." },
        { time: "13:00", mood: "afternoon", title: "Cooking class (my vote)", detail: "Learn Pho, Banh Mi, spring rolls. Actually go home able to cook the food we've been eating.", link: "Cooking Class" },
        { time: "Evening", mood: "evening", title: "Last dinner", detail: "Pick somewhere good. Last proper meal in Vietnam." },
      ],
    },
    {
      n: 13, date: "23 Jun", weekday: "Tue", city: "Hanoi → Melbourne", title: "Departure Day",
      tags: ["Travel"], mood: "morning",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hoan-kiem.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Last walk around Hoan Kiem", detail: "If anyone's up for it. 10-minute stroll from the hotel." },
        { time: "07:30", mood: "morning", title: "Hotel checkout", detail: "Noi Bai is 45 min away. Not negotiable." },
        { time: "09:55", mood: "morning", title: "Wheels up — Hanoi → MEL", detail: "Back in Melbourne by 10:15pm. Then immediately start planning when we can come back." },
      ],
    },
  ],

  hotels: [
    {
      city: "Ho Chi Minh City", name: "Lotus Saigon Hotel", booked: true,
      address: "120 Cách Mạng Tháng Tám, District 3",
      dates: "11 → 15 June · 4 nights",
      tags: ["Rooftop Pool, L19", "Breakfast incl.", "Lift", "District 3"],
      note: "Rooftop pool on level 19 with city views. Breakfast included means mornings are easy. ~45 min Grab from Tan Son Nhat.",
    },
    {
      city: "Hanoi · Stay 1", name: "SQ Hang Gai Hotel & Spa", booked: true,
      address: "100 Hang Gai Street, Hoan Kiem, Hanoi",
      dates: "15 → 18 June · 3 nights",
      tags: ["Breakfast incl.", "Spa", "Old Quarter", "3 rooms"],
      note: "Right on Hang Gai in the heart of the Old Quarter. Check-in from 14:00 — we land late on the 15th so the pre-booked transfer takes us straight here. Two Deluxe rooms (Chris, Jason) plus a Luxury Old Quarter View room (Ashraf). Confirmation 5358747870.",
    },
    {
      city: "Ha Long Bay", name: "Mon Cheri Cruise", booked: true,
      address: "Ha Long Bay, Quang Ninh Province",
      dates: "17 → 18 June · 1 night",
      tags: ["Overnight cruise", "All meals", "Return transfers"],
      note: "One night on the water. Dinner, breakfast, all meals on board.",
    },
    {
      city: "Hanoi · Stay 2", name: "Old Quarter Hotel (TBC)", booked: false,
      address: "Old Quarter, Hoan Kiem District, Hanoi",
      dates: "19 → 23 June · 4 nights",
      tags: ["Breakfast incl.", "Old Quarter"],
      note: "Back from the cruise on the 19th. Old Quarter location keeps everything walkable for the final 4 nights.",
    },
  ],

  phrases: [
    { vn: "Xin chào", say: "sin chow", en: "Hello" },
    { vn: "Cảm ơn", say: "gahm un", en: "Thank you" },
    { vn: "Xin lỗi", say: "sin loy", en: "Sorry / Excuse me" },
    { vn: "Bao nhiêu?", say: "bow nyew", en: "How much?", note: "Use at markets" },
    { vn: "Đắt quá", say: "daht kwah", en: "Too expensive", note: "Haggle line" },
    { vn: "Ngon lắm!", say: "ngon lahm", en: "Delicious!", note: "Say after every meal" },
    { vn: "Không, cảm ơn", say: "khome gahm un", en: "No thank you" },
    { vn: "Tính tiền", say: "ting tyen", en: "Bill please" },
    { vn: "Nước", say: "nuoc", en: "Water" },
    { vn: "...ở đâu?", say: "uh doh", en: "Where is...?" },
    { vn: "Một hai ba, dô!", say: "mot hi ba yo", en: "Cheers!", note: "Most important one" },
    { vn: "Tôi không hiểu", say: "toy khome hyew", en: "I don't understand" },
  ],

  // Weather mocked — varies with current city. Real fetch on a private site is overkill.
  weather: {
    "Ho Chi Minh City": { temp: 32, lo: 26, hi: 34, cond: "Humid · scattered storms PM", icon: "storm", aqi: 78 },
    "Hanoi": { temp: 29, lo: 25, hi: 33, cond: "Hot · muggy", icon: "sun", aqi: 95 },
    "Ha Long Bay": { temp: 28, lo: 24, hi: 31, cond: "Clear over the bay", icon: "sun", aqi: 42 },
    "Ninh Binh": { temp: 30, lo: 24, hi: 33, cond: "Warm · soft cloud", icon: "cloud-sun", aqi: 55 },
  },

  // Stylized SVG-only map route, no Google Maps.
  // Coords are tuned to a 600×800 viewbox roughly mapping Vietnam's S-shape.
  mapPins: [
    { id: "hcmc", label: "Ho Chi Minh City", sub: "11–15 Jun", x: 245, y: 740, labelDir: "right" },
    { id: "mekong", label: "Mekong Delta", sub: "Day trip · 14 Jun", x: 200, y: 770, labelDir: "left" },
    { id: "cuchi", label: "Cu Chi Tunnels", sub: "Day trip · 13 Jun", x: 230, y: 712, labelDir: "left" },
    { id: "ninhbinh", label: "Ninh Binh", sub: "Day trip · 20 Jun", x: 380, y: 260, labelDir: "left" },
    { id: "halong", label: "Ha Long Bay", sub: "Overnight · 17–18 Jun", x: 478, y: 200, labelDir: "right" },
    { id: "hanoi", label: "Hanoi", sub: "15–23 Jun", x: 390, y: 200, labelDir: "left" },
  ],
};
