// Trip data — single source of truth for the Vietnam site
window.TRIP_DATA = {
  meta: {
    title: "The Doos · Vietnam",
    subtitle: "June 2026",
    travelers: ["Christine", "Ashraf", "Jason", "Chris"],
    departDate: "2026-06-11T10:35:00+10:00",
    returnDate: "2026-06-23T22:15:00+10:00",
    nights: 13,
    cities: 2,
  },

  flights: [
    {
      kind: "Outbound",
      from: { city: "Melbourne", code: "MEL", terminal: "T2" },
      to: { city: "Ho Chi Minh City", code: "SGN", terminal: "T2" },
      date: "Thursday 11 June 2026",
      depart: "10:35",
      arrive: "16:15",
      duration: "8h 40m",
      carrier: "Vietnam Airlines",
      flightNo: "VN780",
      aircraft: "Airbus A350",
      note: "Vietnam is 3 hours behind Melbourne. When we land at 4:15 PM your body thinks it's 7:15 PM — manageable. Tan Son Nhat to the hotel in District 3 is about 45 minutes.",
    },
    {
      kind: "Internal",
      from: { city: "Ho Chi Minh City", code: "SGN", terminal: "T1" },
      to: { city: "Hanoi", code: "HAN", terminal: "T1" },
      date: "Monday 15 June 2026",
      depart: "20:30",
      arrive: "22:35",
      duration: "2h 5m",
      carrier: "Vietnam Airlines",
      flightNo: "VN256",
      aircraft: "",
      note: "Late arrival, but no stress. We'll grab a transfer through the Grab app the moment we land. They're everywhere at Noi Bai and dead easy to find, even at midnight.",
    },
    {
      kind: "Return",
      from: { city: "Hanoi", code: "HAN", terminal: "T2" },
      to: { city: "Melbourne", code: "MEL", terminal: "T2" },
      date: "Tuesday 23 June 2026",
      depart: "09:55",
      arrive: "22:15",
      duration: "9h 20m",
      carrier: "Vietnam Airlines",
      flightNo: "VN779",
      aircraft: "Airbus A350-900",
      note: "Hotel checkout 7:30 AM sharp. Yes I know. Last day. Sorry.",
    },
  ],

  days: [
    {
      n: 1, date: "11 Jun", weekday: "Thu", city: "Ho Chi Minh City", title: "Arrival Day",
      tags: ["Travel", "Food", "Easy"], mood: "evening",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hcmc-night.jpg",
      activities: [
        { time: "16:15", mood: "afternoon", title: "Land at Tan Son Nhat", detail: "About 45 minutes by Grab from the airport to the hotel in District 3. Checked in by 5:15pm." },
        { time: "Evening", mood: "evening", title: "Dinner nearby", detail: "Freshen up and find dinner close to the hotel. Don't go too hard on night one." },
        { time: "Later", mood: "night", title: "Rooftop pool (Level 19)", detail: "If anyone's feeling more awake than expected, the rooftop opens until 22:00." },
      ],
      tip: "Use the Grab app for taxis, not the random ones at the airport. Set it up before we land.",
    },
    {
      n: 2, date: "12 Jun", weekday: "Fri", city: "Ho Chi Minh City", title: "History & Markets", /* hero: Ben Thanh Market */
      tags: ["History", "Shopping", "Food"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/ben-thanh.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "War Remnants Museum", detail: "10-minute Grab from the hotel, or 20-min walk if cool enough. Heavy emotionally — take your time. Get there before the heat kicks in.", link: "War Remnants Museum" },
        { time: "Midday", mood: "afternoon", title: "Hotel lunch & cheeky drink", detail: "Midday break. Heat is no joke — grab a cold one and re-set before round two." },
        { time: "Afternoon", mood: "afternoon", title: "Ben Thanh Market", detail: "5-minute Grab, walkable in 15. Souvenirs, coffee, scarves, snacks. Haggle hard — start low and walk away if they won't budge.", link: "Ben Thanh Market" },
        { time: "Evening", mood: "evening", title: "Night market street food", detail: "Ben Thanh turns into a street food market after 6pm. Great way to spend the evening." },
      ],
    },
    {
      n: 3, date: "13 Jun", weekday: "Sat", city: "Ho Chi Minh City", title: "Cu Chi Tunnels",
      tags: ["History", "Outdoors"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/cu-chi.jpg",
      region: {
        base: { name: "Ho Chi Minh City", lat: 10.7769, lng: 106.7009 },
        dest: { name: "Cu Chi Tunnels", lat: 11.1426, lng: 106.4634 },
        bearing: "Northwest",
        distance: "70 km",
        duration: "~1.5 hr drive",
        transport: "Small-group coach",
        terrain: "jungle",
      },
      activities: [
        { time: "08:00", mood: "morning", title: "Tour bus pickup", detail: "1.5 hours northwest of the city. We'll go with a small-group tour, not the giant 40-person buses. Loads to choose from once we're there." },
        { time: "Late morning", mood: "morning", title: "Cu Chi Tunnels", detail: "Jason, you can crawl through the actual tunnels if you want. I'd take the enlarged tourist version unless you're keen to really test yourself.", link: "Cu Chi Tunnels" },
        { time: "Afternoon", mood: "afternoon", title: "Hotel + rooftop pool", detail: "Back by mid-afternoon. You'll have earnt it." },
      ],
      tip: "Everything at your own pace. Plenty of shade and benches, no rushing.",
    },
    {
      n: 4, date: "14 Jun", weekday: "Sun", city: "Ho Chi Minh City", title: "Mekong Delta",
      tags: ["Nature", "Food", "Relaxed"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/mekong-boat.jpg",
      region: {
        base: { name: "Ho Chi Minh City", lat: 10.7769, lng: 106.7009 },
        dest: { name: "Mỹ Tho · Mekong", lat: 10.3600, lng: 106.3650 },
        bearing: "South",
        distance: "70 km",
        duration: "~1.5 hr drive",
        transport: "Coach + canoe",
        terrain: "river",
      },
      activities: [
        { time: "07:30", mood: "morning", title: "Coach to the delta", detail: "1.5 hours south of HCMC. Canals, rice paddies, coconut palms, small fishing villages." },
        { time: "Morning", mood: "morning", title: "Coconut candy factory", detail: "Mum — this one's for you. Plus a bee farm and a tropical fruit garden with live traditional music." },
        { time: "Afternoon", mood: "afternoon", title: "Canal canoe ride", detail: "Local rowers take you through the jungle. Just sit back. Lunch included.", link: "Mekong Delta Boat Tour" },
        { time: "Evening", mood: "evening", title: "Last dinner in HCMC", detail: "Let's find somewhere good. Last night in the south." },
      ],
    },
    {
      n: 5, date: "15 Jun", weekday: "Mon", city: "HCMC → Hanoi", title: "Fly North",
      tags: ["Relax", "Travel"], mood: "evening",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hanoi-old-quarter.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Free morning", detail: "Sleep in, rooftop pool one last time, leisurely breakfast." },
        { time: "17:30", mood: "evening", title: "Leave for airport", detail: "Tan Son Nhat is ~40 min from District 3. Aim to leave by 5:30pm for the 8:30pm departure." },
        { time: "22:35", mood: "night", title: "Land in Hanoi", detail: "Open the Grab app and book a car straight to the Old Quarter. Easy to find even this late. Noi Bai is ~45 min away. Bed." },
      ],
    },
    {
      n: 6, date: "16 Jun", weekday: "Tue", city: "Hanoi", title: "Old Quarter & Hoa Lo",
      tags: ["History", "Food", "Shopping"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hoan-kiem.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Slow breakfast", detail: "Hanoi feels completely different — older, cooler, more French colonial. Just take it in." },
        { time: "Late morning", mood: "morning", title: "Hoa Lo Prison", detail: "10-minute walk from most Old Quarter hotels. Covers French colonial era and the Vietnam War. Get the audio guide.", link: "Hoa Lo Prison" },
        { time: "Afternoon", mood: "afternoon", title: "Hoan Kiem Lake", detail: "10 min on foot from Hoa Lo. Little temple on an island connected by a red bridge — really beautiful." },
        { time: "Afternoon", mood: "afternoon", title: "Old Quarter wander", detail: "The 36 streets. You could walk it end-to-end in 20 min — you won't." },
        { time: "Evening", mood: "evening", title: "Street food + egg coffee", detail: "Try the egg coffee. Tastes like liquid tiramisu." },
      ],
    },
    {
      n: 7, date: "17 Jun", weekday: "Wed", city: "Hanoi", title: "Temple & Shopping",
      tags: ["Culture", "Shopping", "Easy"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/temple-literature.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Slow start", detail: "No rush today. Proper breakfast before an easy day around the Old Quarter." },
        { time: "Late morning", mood: "morning", title: "Temple of Literature", detail: "15-min Grab from the Old Quarter. Vietnam's first university — built in 1070. Hire a guide; the history is what makes it.", link: "Temple of Literature" },
        { time: "Afternoon", mood: "afternoon", title: "Hang Gai & Dong Xuan", detail: "Old Quarter shopping. Walkable from the hotel. Pack light for the cruise tomorrow — leave the big bags at the hotel." },
        { time: "Evening", mood: "evening", title: "Cha Ca La Vong", detail: "Turmeric fish cooked at the table with dill. Worth trying." },
      ],
    },
    {
      n: 8, date: "18 Jun", weekday: "Thu", city: "Hanoi → Ha Long Bay", title: "Mon Cheri Cruise",
      tags: ["Nature", "Food", "Unmissable"], mood: "day", star: true,
      hero: "https://doosyy.github.io/Vietnam-Trip/img/halong-cruise.jpg",
      region: {
        base: { name: "Hanoi · Old Quarter", lat: 21.0278, lng: 105.8342 },
        dest: { name: "Hạ Long City", lat: 20.9101, lng: 107.1839 },
        bearing: "East",
        distance: "170 km",
        duration: "~3.5 hr drive",
        transport: "Shuttle bus → cruise",
        terrain: "bay",
      },
      activities: [
        { time: "08:00", mood: "morning", title: "Luxury shuttle pickup", detail: "Luxury shuttle bus from the Old Quarter to Ha Long, included in the cruise package. ~3.5 hours. Arrive at the harbour around 11:30am." },
        { time: "12:00", mood: "afternoon", title: "Board Mon Cheri + lunch on deck", detail: "The moment the limestone karsts appear around you, everyone goes quiet. It does that to people." },
        { time: "Afternoon", mood: "afternoon", title: "Cave visit + optional kayaking", detail: "Kayaking is included and completely optional — you can sit on the deck and let the views do the work." },
        { time: "Sunset", mood: "evening", title: "Sunset on deck + seafood dinner", detail: "Drinks on deck, dinner on board, sleep on the boat.", link: "Ha Long Bay Cruise" },
      ],
    },
    {
      n: 9, date: "19 Jun", weekday: "Fri", city: "Ha Long Bay → Hanoi", title: "Sunrise on the Bay",
      tags: ["Nature"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/halong-bay.jpg",
      activities: [
        { time: "Sunrise", mood: "morning", title: "Sunrise on deck", detail: "Set an alarm. Worth it." },
        { time: "Morning", mood: "morning", title: "Breakfast + sail back", detail: "Slow morning on board before disembarking." },
        { time: "Afternoon", mood: "afternoon", title: "Shuttle back to Hanoi", detail: "Same luxury shuttle bus back to the Old Quarter. ~3.5 hours. Check into our final Hanoi stay by early evening." },
      ],
    },
    {
      n: 10, date: "20 Jun", weekday: "Sat", city: "Ninh Binh", title: "Ha Long on Land",
      tags: ["Nature", "History", "Scenic"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/ninh-binh.jpg",
      region: {
        base: { name: "Hanoi · Old Quarter", lat: 21.0278, lng: 105.8342 },
        dest: { name: "Trang An · Ninh Binh", lat: 20.2506, lng: 105.9745 },
        bearing: "South",
        distance: "95 km",
        duration: "~2 hr drive",
        transport: "Private coach",
        terrain: "karst",
      },
      activities: [
        { time: "07:30", mood: "morning", title: "Drive south", detail: "2 hours to Ninh Binh. Called the inland Ha Long Bay — same dramatic limestone karsts but surrounded by rice paddies." },
        { time: "Morning", mood: "morning", title: "Trang An boat trip", detail: "Local rowers take us through caves, past ancient temples, under limestone cliffs. ~2.5 hours. Sit and take it in.", link: "Ninh Binh & Trang An" },
        { time: "Afternoon", mood: "afternoon", title: "Lunch in town", detail: "Local speciality is goat meat. Don't knock it until you've tried it." },
        { time: "Evening", mood: "evening", title: "Back to Hanoi", detail: "Quiet night." },
      ],
    },
    {
      n: 11, date: "21 Jun", weekday: "Sun", city: "Hanoi", title: "Chill & Street Food",
      tags: ["Food", "Relaxed"], mood: "evening",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/street-food.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Coffee by Hoan Kiem", detail: "10 min from the hotel. Locals do tai chi here. Just sit and watch the city wake up." },
        { time: "Afternoon", mood: "afternoon", title: "Spa, shopping & bar hopping", detail: "Mum — strongly recommend a spa. Vietnamese massage is exceptional and very affordable. Plenty of boutiques in the Old Quarter, then drinks before dinner. Jason can find his own trouble." },
        { time: "18:30", mood: "evening", title: "Old Quarter street food tour", detail: "~3 hours. Banh Mi, egg coffee, spring rolls, Che. Go in with an open mind on that last one.", link: "Street Food Tour" },
      ],
      tip: "Egg coffee is a Hanoi original — Cafe Giang on Hang Gai Street is the famous one, but honestly most cafes do a great version. Don't go out of your way; grab one whenever you see it.",
    },
    {
      n: 12, date: "22 Jun", weekday: "Mon", city: "Hanoi", title: "Flex Day",
      tags: ["Food", "Hands-on", "Free"], mood: "day",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/pho.jpg",
      activities: [
        { time: "Flexible", mood: "morning", title: "Knife-forging class (optional)", detail: "For anyone keen on something properly hands-on: forge your own knife with the blacksmiths at Da Sy village, just outside Hanoi. About 4 hours with hotel pickup from the Old Quarter, and you take the finished knife home. Around US$60 per person, private group of up to 5. Start times are flexible: 08:30, 10:00, 13:00 or 14:00, so we can fit it around the cooking class and last dinner. Jason, this one has your name on it.", url: "https://atasteofhanoi.com/hanoi-tours/day-tours/knives-making-class/" },
        { time: "Morning", mood: "morning", title: "Or take it easy — shopping", detail: "Not feeling the forge? By this point we'll know what we feel like. Good morning for last-minute shopping in the Old Quarter: souvenirs, silk, art prints, anything you've been eyeing all week. Don't over-plan it." },
        { time: "13:00", mood: "afternoon", title: "Cooking class (my vote)", detail: "Learn Pho, Banh Mi, spring rolls. Actually go home able to cook the food we've been eating.", link: "Cooking Class" },
        { time: "Evening", mood: "evening", title: "Last dinner", detail: "Pick somewhere good. Last proper meal in Vietnam." },
      ],
    },
    {
      n: 13, date: "23 Jun", weekday: "Tue", city: "Hanoi → Melbourne", title: "Departure Day",
      tags: ["Travel"], mood: "morning",
      hero: "https://doosyy.github.io/Vietnam-Trip/img/hoan-kiem.jpg",
      activities: [
        { time: "Morning", mood: "morning", title: "Last walk around Hoan Kiem", detail: "If anyone's up for it. 10-minute stroll from the hotel." },
        { time: "07:30", mood: "morning", title: "Hotel checkout", detail: "Noi Bai is 45 min away. Not negotiable." },
        { time: "09:55", mood: "morning", title: "Wheels up — Hanoi → MEL", detail: "Back in Melbourne by 10:15pm. Then immediately start planning when we can come back." },
      ],
    },
  ],

  hotels: [
    {
      city: "Ho Chi Minh City", name: "Lotus Saigon Hotel", booked: true,
      address: "120 Cách Mạng Tháng Tám, District 3",
      dates: "11 → 15 June · 4 nights",
      tags: ["Rooftop Pool, L19", "Breakfast incl.", "Lift", "District 3"],
      note: "Rooftop pool on level 19 with city views. Breakfast included means mornings are easy. ~45 min Grab from Tan Son Nhat.",
    },
    {
      city: "Hanoi · Stay 1", name: "SQ Hang Gai Hotel & Spa", booked: true,
      address: "100 Hang Gai Street, Hoan Kiem, Hanoi",
      dates: "15 → 18 June · 3 nights",
      tags: ["Breakfast incl.", "Spa", "Old Quarter", "3 rooms"],
      note: "Right on Hang Gai in the heart of the Old Quarter. Check-in from 14:00 — we land late on the 15th, so we'll just book a Grab at the airport and be here in ~45 min. Two Deluxe rooms (Chris, Jason) plus a Luxury Old Quarter View room (Ashraf). Confirmation 5358747870.",
    },
    {
      city: "Ha Long Bay", name: "Mon Cheri Cruise", booked: true,
      address: "Ha Long Bay, Quang Ninh Province",
      dates: "18 → 19 June · 1 night",
      tags: ["Ocean Suite Balcony", "All meals", "Shuttle incl.", "Kayaking"],
      note: "Ocean Suite Balcony (twin) for the four of us. One night on the water with all meals on board, plus free kayaking. Luxury shuttle bus round trip Hanoi ⇄ Ha Long is included. Booking code 190282.",
    },
    {
      city: "Hanoi · Stay 2", name: "Old Quarter Hotel (TBC)", booked: false,
      address: "Old Quarter, Hoan Kiem District, Hanoi",
      dates: "19 → 23 June · 4 nights",
      tags: ["Breakfast incl.", "Old Quarter"],
      note: "Back from the cruise on the 19th. Old Quarter location keeps everything walkable for the final 4 nights.",
    },
  ],

  phrases: [
    { vn: "Xin chào", say: "sin chow", en: "Hello" },
    { vn: "Cảm ơn", say: "gahm un", en: "Thank you" },
    { vn: "Xin lỗi", say: "sin loy", en: "Sorry / Excuse me" },
    { vn: "Bao nhiêu?", say: "bow nyew", en: "How much?", note: "Use at markets" },
    { vn: "Đắt quá", say: "daht kwah", en: "Too expensive", note: "Haggle line" },
    { vn: "Ngon lắm!", say: "ngon lahm", en: "Delicious!", note: "Say after every meal" },
    { vn: "Không, cảm ơn", say: "khome gahm un", en: "No thank you" },
    { vn: "Tính tiền", say: "ting tyen", en: "Bill please" },
    { vn: "Nước", say: "nuoc", en: "Water" },
    { vn: "...ở đâu?", say: "uh doh", en: "Where is...?" },
    { vn: "Một hai ba, dô!", say: "mot hi ba yo", en: "Cheers!", note: "Most important one" },
    { vn: "Tôi không hiểu", say: "toy khome hyew", en: "I don't understand" },
  ],

  // Fallback weather only — live values are fetched from Open-Meteo in the app.
  // These show if the live fetch fails or before it resolves.
  weather: {
    "Ho Chi Minh City": { temp: 32, lo: 26, hi: 34, cond: "Humid · scattered storms PM", icon: "storm", aqi: 78 },
    "Hanoi": { temp: 29, lo: 25, hi: 33, cond: "Hot · muggy", icon: "sun", aqi: 95 },
    "Ha Long Bay": { temp: 28, lo: 24, hi: 31, cond: "Clear over the bay", icon: "sun", aqi: 42 },
    "Ninh Binh": { temp: 30, lo: 24, hi: 33, cond: "Warm · soft cloud", icon: "cloud-sun", aqi: 55 },
  },

  // Real coordinates (lat/lng) — rendered on an interactive Leaflet map.
  // routeOrder below sets the south-to-north line drawn between stops.
  routeOrder: ["hcmc", "cuchi", "mekong", "hanoi", "halong", "ninhbinh"],
  mapPins: [
    { id: "hcmc", label: "Ho Chi Minh City", sub: "11–15 Jun", lat: 10.7769, lng: 106.7009 },
    { id: "mekong", label: "Mekong Delta", sub: "Day trip · 14 Jun", lat: 10.3600, lng: 106.3650 },
    { id: "cuchi", label: "Cu Chi Tunnels", sub: "Day trip · 13 Jun", lat: 11.1426, lng: 106.4634 },
    { id: "ninhbinh", label: "Ninh Binh", sub: "Day trip · 20 Jun", lat: 20.2506, lng: 105.9745 },
    { id: "halong", label: "Ha Long Bay", sub: "Overnight · 18–19 Jun", lat: 20.9101, lng: 107.1839 },
    { id: "hanoi", label: "Hanoi", sub: "15–23 Jun", lat: 21.0278, lng: 105.8342 },
  ],
};
